info:
  name: Get environment relations
  type: http
  seq: 9

http:
  method: GET
  url: https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/environment
  auth: inherit

runtime:
  scripts:
    - type: after-response
      code: |-
        test("Status code is 200", function () {
            expect(res.getStatus()).to.equal(200);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Successful Response
    request:
      url: https://api.getpostman.com/apis/387c2863-6ee3-4a56-8210-225f774edade/versions/a9879d02-74bf-425a-bbec-6d27aa135507/environment
      method: GET
    response:
      statusText: "200"
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
              "environment": [
                  {
                      "id": "12345678-5daabc50-8451-43f6-922d-96b403b4f28e",
                      "name": "Test Environment",
                      "createdAt": "2022-07-08T20:32:48.000Z",
                      "updatedAt": "2022-07-08T20:31:30.000Z"
                  }
              ]
          }
  - name: Rate Limit Exceeded
    request:
      url: https://api.getpostman.com/apis/387c2863-6ee3-4a56-8210-225f774edade/versions/a9879d02-74bf-425a-bbec-6d27aa135507/environment
      method: GET
    response:
      statusText: "429"
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
              "error": "rateLimited",
              "message": "Rate limit exceeded. Please retry after 1669048687"
          }

docs: |-
  **This endpoint is deprecated in Postman v10 and higher.**

  Gets an API version's environment relations.
